version: "3.8"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/basics?allowPublicKeyRetrieval=true
      - spring.datasource.username=admin
      - spring.datasource.password=s3cret
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: basics
      MYSQL_USER: admin
      MYSQL_PASSWORD: s3cret
      MYSQL_ROOT_PASSWORD: root

networks:
  springapimysql-net:
